### ISSUE TITLE
Add logic for break reminder

### ISSUE THREAD

**Issue by BrianPearTree** [sujith90/Pi#16]
One of our technical requirements is to have a configurable break reminder. <br>
Add the logic to the code to require a break - after a the employee is in cubical for a configurable amount of time?
This is part of our stretch requirement to improve health of the worker.

**Comment by noebrito** [comment]
@BrianPearTree Issue for the ETS reminder if you leave your cube within X minutes of a configurable time?

**Comment by BrianPearTree** [comment]
If I understand your question correctly, if you have x set to 45 minutes and you leave your cube 44 minutes before ets time, an alarm will sound to remind you to fill out your time card. 

I suppose you could use a visual reminder at 45 mins whether you are in the cube or not. I'm not sure how annoying that would be, but it could be turned off.

**Comment by BrianPearTree** [comment]
@btbam91 btw

**Comment by noebrito** [comment]
@BrianPearTree sorry, I should really speak in complete sentences. My intent was to ask if you plan on creating an "issue" for that feature.

**Comment by noebrito** [comment]
I will get this done ASAP. I do not expect it to be too difficult.

**Comment by noebrito** [comment]
80% done with this feature. Sorry it's taking so long... I barely started working on it today. I drank a red bull to make sure I finish the majority of it tonight. :)

**Comment by noebrito** [comment]
I am closing this issue. As we discussed, the logic is currently tied to the Break Screen in the UI. Need to integrate with Sujith to tie the logic to OMRON data.

<img width="229" alt="settingsnextbutton" src="https://cloud.githubusercontent.com/assets/15386865/12832108/f96e93c8-cb4c-11e5-8ac1-a21440b1288f.png">

<img width="228" alt="settingsbreakreminder" src="https://cloud.githubusercontent.com/assets/15386865/12832112/ff7144d2-cb4c-11e5-8e26-69f4da88a6ad.png">

Demo: [http://www.screencast.com/t/tyvtJomV1]
