### ISSUE TITLE
Create an ETS reminder

### ISSUE THREAD

**Issue by BrianPearTree** [sujith90/Pi#18]
Within x minutes if time to leave, if the employee leaves desk without notifying monkey time card is filled out, give a gentle reminder!

**Comment by noebrito** [comment]
![settings1](https://cloud.githubusercontent.com/assets/15386865/12370381/9843c5b6-bbc3-11e5-9a93-6f2917ee72f3.jpg)
![settings2](https://cloud.githubusercontent.com/assets/15386865/12370382/985cbb48-bbc3-11e5-8d23-62e7bdc7b6df.jpg)

Making good progress here.... Learned how to save and persist settings using .json files. Much easier than just writing to a .txt file.

**Comment by noebrito** [comment]
The "Settings" aspect of this feature is implemented . The user can set the 1. Time that the user leaves work and 2. The x amount of minutes within the time time. The settings properly persist as the application is opened and closed.

**Comment by noebrito** [comment]
<img width="207" alt="main_screen" src="https://cloud.githubusercontent.com/assets/15386865/12524623/31001f94-c113-11e5-82c9-64d65206d25f.png">
<img width="195" alt="settings_screen" src="https://cloud.githubusercontent.com/assets/15386865/12524624/31187260-c113-11e5-9bdf-447ee475fccc.png">

I believe I have finished implementing this feature. I won't be able to make the meeting on Monday so I recorded a demo of the functionality in action: http://www.screencast.com/t/VygEugb7OV5

I checked in the code to Github.

**Comment by BrianPearTree** [comment]
Wow! This is really cool. Nice implementation, great demo.
