### ISSUE TITLE
Scale GUI to touchscreen, fill gaps and integrate Omron/Servo code

### ISSUE THREAD

**Issue by BrianPearTree** [sujith90/Pi#2]
@sujith90 @btbam91

**Comment by noebrito** [comment]
Will work on getting the GUI running on the Pi touchscreen today.

**Comment by noebrito** [comment]
Got the GUI running on the touchscreen no problem. Next step is optimizing it so that the buttons are larger and easier to press.

**Comment by BrianPearTree** [comment]
Experimented with scaling. Need to test it out on the touch screen.

**Comment by BrianPearTree** [comment]
@sujith90 Worked on threading. Still need to test on Raspberry PI.

**Comment by BrianPearTree** [comment]
Noe got this working on the touchscreen, moving to close.
