### ISSUE TITLE
Monkey Quiet Mode

### ISSUE THREAD

**Issue by BrianPearTree** [sujith90/Pi#29]
Visual cue LEDs if monkey is disabled show LEDs flashing or some other visual indicator instead..

**Comment by noebrito** [comment]
Added a "General Settings" screen where the user can deactivate the monkey. I won't be closing this issue as the UI code still has to integrate with the LED...

<img width="221" alt="generalsettingsscreen" src="https://cloud.githubusercontent.com/assets/15386865/12908851/867b8db0-ceaf-11e5-9122-2bb29ccf2a87.png">

**Comment by noebrito** [comment]
This feature is done.
