### ISSUE TITLE
What time is it?

### ISSUE THREAD

**Issue by BrianPearTree** [sujith90/Pi#30]
Figure out how to persist time on the pi.

**Comment by noebrito** [comment]
The Pi does not persist time unless we add a real time clock. I think it is too late to order a new part...

So, we can change the timezone of the Pi to pacific time and make sure the Pi is connected to the internet. On boot up the Pi will grab the current date and time from the internet. I assume we will likely connect the Pi to a mobile hotspot when it's time to demo. I have confirmed that the Pi will automatically connect to the internet on bootup.
