### ISSUE TITLE
Design alternative presence indicator with RGB LEDs

### ISSUE THREAD

**Issue by BrianPearTree** [sujith90/Pi#7]
If IR range won't increase, we'll need to get an alternative, wired presence indicator.

**Comment by BrianPearTree** [comment]
I think we have something that will work, but some soldering will be required.

**Comment by noebrito** [comment]
@BrianPearTree What's the intent of this issue?

**Comment by BrianPearTree** [comment]
This is the 3 RGB lights we have, but this isn't complete until we have designed the packaging around it. The space shuttle/747 thing won't print. We'll need to pick something else. It doesn't have to even be 3d printed.

**Comment by noebrito** [comment]
Make the executive decision boss!

**Comment by BrianPearTree** [comment]
Sujith soldered this 2/21 and it works pretty well. I think the added resistance of the solder tweaked the color of the 3rd LED in the series.The casing is very attractive.
